# -*- coding: utf-8 -*-
"""json_total

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13jRa9dLjLUc7GKPYstvXXbqmghmAt7YE
"""

import json
import pandas as pd
from google.colab import files

from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/MyDrive/json/openalexco.json','r') as miarchivo:
    objeto=miarchivo.read()
objeto=json.loads(objeto)

# https://ror.org/03bp5hc83 ror de la udea

objeto=[ c for c in objeto if any(
    [ any([i.get('ror')=="https://ror.org/03bp5hc83" for i in a.get('institutions')]) 
    for a in c.get('authorships')])
]

[ [ [i.get('ror')=="https://ror.org/03bp5hc83" for i in a.get('institutions')] for a in c.get('authorships')] for c in objeto][0]

def filter_concept(concepts,concept='Physics'):
    return any([True for c in concepts if c.get('display_name')==concept])

def filter_ror(authorships,ror="https://ror.org/03bp5hc83"):
  return any([any([i.get('ror')=="https://ror.org/03bp5hc83" for i in a.get('institutions')])  for a in authorships])

ph=[d for d in objeto if filter_concept(d.get('concepts'),concept='Physics') ] #Aqui ya se filtro los conceptos de Física
del(objeto)

len(ph)

pp    = [d for d in ph if (filter_concept(d.get('concepts'),concept='Condensed matter physics') or
                           filter_concept(d.get('concepts'),concept='Nanotechnology')
                           ) ]
len(pp)

pp_level2=[d for d in ph if (filter_concept(d.get('concepts'),concept='Thin film') or
                             filter_concept(d.get('concepts'),concept='Ferromagnetism')
                             ) ]
len(pp_level2)

import pandas as pd

df=pd.DataFrame(pp_level2)
df

js = df.to_json('/content/drive/MyDrive/json/OpenAlex Condensed matter physics.json', orient = 'columns')